# Introduction
Deep learning with satellite imagery is a rapidly growing field that combines the power of artificial intelligence with satellite imagery to tackle complex problems. Satellite imagery has become an important source of information for a variety of industries, including agriculture, climate monitoring, and urban planning. Deep learning algorithms can be applied to satellite imagery to perform tasks such as image classification, object detection, and segmentation. In this chapter, we will explore the fundamental concepts of deep learning and its applications in the context of satellite imagery. We will also discuss some of the challenges and limitations of using deep learning with satellite imagery and explore some of the recent advancements in this field.

# What is satellite imagery?

Satellite imagery is a type of aerial imagery that is captured by satellites orbiting the Earth. Satellite imagery is used for a variety of purposes, including monitoring natural disasters, mapping the Earth, and monitoring crop health. Satellite imagery is also used in the field of remote sensing, which is the science of collecting information about an object or area from a distance. Remote sensing is used in a variety of fields, including agriculture, climate monitoring, and urban planning.


## What is satellite & aerial imagery?
Give a motivation for applying machine learning to satellite & aerial imagery. This could include:

- The large amount of imagery being generated
- The need for rapid analysis of imagery, e.g. in disaster response scenario
- The need for automated analysis of imagery, e.g. in the case of large scale crop monitoring

## What is machine learning?
Machine learning is an approach in which models are trained to find patterns in data.
Machine learning techniques have long been applied to satellite & aerial imagery. Examples include the use of clustering techniques to identify crop types. Etc

## What is deep learning?
Deep learning techniques for vision came to prominence in 2012 when AlexNet won the ImageNet Large Scale Visual Recognition Challenge (ILSVRC). AlexNet is a convolutional neural network (CNN), and in the years since then CNN based neural network techniques have been applied to a wide range of vision tasks including object detection, semantic segmentation, image captioning.

Diagram of a CNN

## The unique challenges of working with satellite & aerial imagery
Compared to working with regular images found on the interet, working with satellite & aerial imagery presents a number of unique challenges. These include:

- Large images
- Many channels
- Unusual orientation of objects
- Large range of object sizes
- Non standard file formats
- Wide range of imaging modalities including SAR, multispectral, hyperspectral, thermal, etc



